- src/main/java/xyz/wagyourtail/jsmacros/client/JsMacros.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/classes/Draw3D.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/classes/PlayerInput.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/helpers/ClientPlayerEntityHelper.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/library/impl/FPlayer.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/sharedclasses/PositionCommon.java
- src/main/java/xyz/wagyourtail/jsmacros/client/mixins/events/MixinClientPlayerEntity.java
- src/main/java/xyz/wagyourtail/jsmacros/client/movement/MovementDummy.java
- src/main/java/xyz/wagyourtail/jsmacros/client/movement/MovementQueue.java
Well the title says it.
The biggest new scripting thing, is the introduction of the class `PlayerInput`, which combines all player inputs into one object.
It is possible to create `PlayerInput` objects through CSV or JSON strings.
The cool thing though is that it is possible to predict, where the inputs will lead:
[Example](https://i.imgur.com/77EHmRg.mp4)
And example on how to read a CSV file:
```js
const PlayerInput = Java.type("xyz.wagyourtail.jsmacros.client.api.classes.PlayerInput")
let csv = FS.open("inputs.csv").read()
let inputs = PlayerInput.fromCsv(csv, ",")
```
Or define your own inputs:
```js
const PlayerInput = Java.type("xyz.wagyourtail.jsmacros.client.api.classes.PlayerInput")
var inputs = new java.util.ArrayList() 
let input1 = new PlayerInput(1, 0, 0)
for (i = 0; i < 10; …
```
> Predict movement using player inputs.

- README.md
I didn't like the look of the old readme and it was lacking information.
Maybe this can also be used for the curseforge page?
> Readme redo

- src/main/java/xyz/wagyourtail/jsmacros/client/api/classes/PlayerInput.java
- src/main/java/xyz/wagyourtail/jsmacros/client/movement/MovementDummy.java
- src/main/java/xyz/wagyourtail/jsmacros/client/movement/MovementQueue.java
* There was a bug, that the MovementQueue would recalculate the predictions even though the player wasn't deviating from the path.
* I added a input history to the MovementDummy, since this is very helpful for path finding.
* Furthermore I made the MovementDummy clonable, also useful for path finding.
* I removed the armorItems list, since this is never used.
* The csv stuff was not working bc there was a new object(the gson object) in the class, which messed a lot of stuff up.
> Bug fixes and improvements for the movement stuff

- .github/workflows/beta.yml
- .github/workflows/buildrelease.yml
- build.gradle
- buildSrc/src/main/java/xyz/wagyourtail/doclet/pydoclet/Main.java
- buildSrc/src/main/java/xyz/wagyourtail/doclet/pydoclet/parsers/ClassParser.java
- pydoc/README.md
- src/main/java/xyz/wagyourtail/jsmacros/client/mixins/events/MixinClientPlayerEntity.java
Before Merge add PyPI API Token. How?
> JsMacrosAC Package Generator

- buildSrc/src/main/java/xyz/wagyourtail/doclet/pydoclet/Main.java
- buildSrc/src/main/java/xyz/wagyourtail/doclet/pydoclet/parsers/ClassParser.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/library/impl/FPlayer.java
- Added Docstring to Methods/Classes
- Changed some return tags
> JsMacrosAC Changes

- src/main/java/xyz/wagyourtail/jsmacros/client/mixins/events/MixinClientPlayNetworkHandler.java
Known problem(s):
Title events trigger twice.
With help of Discord @Etheradon#2766
Signed-off-by: Hampus Toft <hamtof-0@student.ltu.se>
> Added actionbar to Events, Also fixed existing subtitle.

- src/main/java/xyz/wagyourtail/jsmacros/client/api/classes/BeaconInventory.java
Fixed a few bugs with selecting the the beacon effects.
> Fixed beacon inventory bug

- src/main/java/xyz/wagyourtail/jsmacros/client/access/IMixinEntity.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/helpers/EntityHelper.java
- src/main/java/xyz/wagyourtail/jsmacros/client/mixins/access/MixinEntity.java
This should finally fix the glowing color bug for 1.17.
> Fixed Glowing Color

- common/src/main/java/xyz/wagyourtail/jsmacros/client/api/library/impl/FClient.java
> Added loadWorld to FClient so you can also open SP worlds

- common/src/main/java/xyz/wagyourtail/jsmacros/client/api/library/impl/FClient.java
I honestly have no idea why it happens but this fixes it sooo
> Fix baritone crashes due to nullified server info

- docs/python/README.md
Added a space btw the # and the title
> Typo in Python Readme

- common/src/main/java/xyz/wagyourtail/jsmacros/client/api/library/impl/FWorld.java
This adds a alternative getBiomeAt() method where someone can declare a y parameter
> add getBiomeAt(x,y,z)

- src/core/java/xyz/wagyourtail/jsmacros/core/threads/JsMacrosThreadPool.java
This seems to fix #113.
I changed the `JsMacrosThreadPool` to not reuse threads.
> fix deadlock by not reusing threads, simplifying synchronization logic

- buildSrc/src/main/java/xyz/wagyourtail/doclet/tsdoclet/parsers/AbstractParser.java
changes:
* remove unnecessary (empty) `@param` and `@return`
* proper `@code` parsing (`{@code some code}` to `` `some code` ``)
* fix type param parsing (`@param <T> desc` to `@template T desc`)
* fix vscode's jsdoc parsing when `{@...}` is right after `@return`
* convert signature format in `@link` and `@see`
> Improve jsdoclet comment parsing

- src/core/java/xyz/wagyourtail/jsmacros/core/library/impl/classes/ClassBuilder.java
- src/core/java/xyz/wagyourtail/jsmacros/core/library/impl/classes/LibraryBuilder.java
Fix a bug that prevents saving array content to the builder.
> Fix AnnotationArrayBuilder finish method

- src/main/java/xyz/wagyourtail/jsmacros/client/api/library/impl/FWorld.java
Make rayTraceBlock and rayTraceEntity compatible with double and not only integers.
> Make rayTraceBlock and rayTraceEntity compatible with double 

- src/main/java/xyz/wagyourtail/jsmacros/client/api/classes/render/Draw3D.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/classes/render/components3d/EntityTraceLine.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/classes/render/components3d/TraceLine.java
java implementation of [this](https://discord.com/channels/732004268948586545/1074990648928772147)
> add TraceLine component

- src/main/java/xyz/wagyourtail/jsmacros/client/api/event/impl/EventMouseScroll.java
- src/main/java/xyz/wagyourtail/jsmacros/client/config/Profile.java
- src/main/java/xyz/wagyourtail/jsmacros/client/mixins/events/MixinMouse.java
add `MouseScroll` event so people can control service by scrolling
> MouseScroll event

- src/main/java/xyz/wagyourtail/jsmacros/client/access/IClientPlayerInteractionManager.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/classes/InteractionProxy.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/helpers/InteractionManagerHelper.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/helpers/world/entity/ClientPlayerEntityHelper.java
- src/main/java/xyz/wagyourtail/jsmacros/client/api/library/impl/FPlayer.java
- src/main/java/xyz/wagyourtail/jsmacros/client/mixins/access/MixinClientPlayerInteractionManager.java
- src/main/java/xyz/wagyourtail/jsmacros/client/mixins/access/MixinMinecraftClient.java
move interaction related methods to `InteractionManagerHelper` ([Discord Message](https://discord.com/channels/732004268948586545/732006115000451143/1142633767962431498))
fix race condition issue when breaking instabreakable block using `breakBlock()`
> Move and fix interaction related methods

- src/main/java/xyz/wagyourtail/jsmacros/client/api/helpers/world/entity/ClientPlayerEntityHelper.java
because setPos on script thread might cause ConcurrentModificationException
> setPos on main thread

- src/main/java/xyz/wagyourtail/jsmacros/client/api/library/impl/FUtils.java
since there's some nullable methods that returns null when world is not loaded, and sometimes we expect a script to run while in a world, then this method can conveniently assert the return value. (mainly for typescript)
[related discord message](https://discord.com/channels/732004268948586545/739655736296210442/1224685131088789636)
> Add requireNonNull in FUtils
